version: '2.2'

services:
  app:
    image: 'ddss-storage:latest'
    build:
      context: .
    container_name: ddss-storage-app
    networks:
      - my-net
    ports:
      - '8081:8081'
    depends_on:
      - db
    command: sh -c './wait-for host:5433'
    env_file:
      - vars-spring.env
          
  db:
    image: 'postgres:14.2-alpine'
    container_name: ddss-storage-db
    networks:
      - my-net
    ports:
      - '5433:5433'
    command: -p 5433
    env_file:
      - vars-postgres.env

networks:
  my-net:
    external: true
