// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/sensors-data.proto

package ddss.device.proto;

public interface SensorsDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensorsData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 degrees_celsius = 1;</code>
   * @return The degreesCelsius.
   */
  int getDegreesCelsius();

  /**
   * <code>int32 pascals = 2;</code>
   * @return The pascals.
   */
  int getPascals();

  /**
   * <code>int32 meters_per_second = 3;</code>
   * @return The metersPerSecond.
   */
  int getMetersPerSecond();
}
