// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/HelloService.proto

package ssau.kuznetsov.proto;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ssau.kuznetsov.proto.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
